import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import Providers from "@/utils/Provider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Zef-Blog",
  description: "Generated by Mohamed Elzefzafy",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {

    const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en" dir="ltr">
      <body className={inter.className}>
        
  <NextIntlClientProvider>  
    <Providers>
          <CssBaseline />
      {children}
          </Providers>
      </NextIntlClientProvider>
      
    
      </body>
    </html>
  );
}




