import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import Providers from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Zef-Blog",
  description: "Generated by Mohamed Elzefzafy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CssBaseline />

          {children}
        </Providers>
      </body>
    </html>
  );
}
